### ISSUE TITLE
Line spacing in layers and maps lists should be 1.5

### ISSUE THREAD

**Issue by timlinux** [kartoza/least-cost-electrification-somaliland#1]
![image](https://user-images.githubusercontent.com/178003/133095848-60e018dd-e2a9-4024-9223-1ea370810bef.png)

Dont enable globally, just for the descriptions

**Comment by lkwalke4** [comment]
@meomancer Any update on this issue?

**Comment by meomancer** [comment]
This has been updated and deployed
could you check this @lkwalke4 ?

**Comment by lkwalke4** [comment]
@meomancer Looks good! I'll close this issue.
