### ISSUE TITLE
Admin Label

### ISSUE THREAD

**Issue by meomancer** [kartoza/least-cost-electrification-somaliland#10]
From Alex

> The new base map you developed has the wrong label for one of the administrative areas. So, what is referred as "Waqoyi Galbeed" should be updated to "Maroodi Jeex" (same as in filters). The name was recently updated, and we didn't include this on the admin file we originally shared.

**Comment by seabilwe** [comment]
Hi @meomancer I changed the name

![Peek 2021-10-12 21-04](https://user-images.githubusercontent.com/56301949/137014485-1044d0cc-c76e-4171-bb4f-af63e95d4a7f.gif)

**Comment by meomancer** [comment]
great, thank you @seabilwe 
it's changed
