### ISSUE TITLE
Multiple legend entries for the same feature class

### ISSUE THREAD

**Issue by vermeulendivan** [kartoza/least-cost-electrification-somaliland#14]
Multiple legend entries for the same feature class. This happens because those classes displays at different scale. See below (those are the same features, but rules for different scales):
![image](https://user-images.githubusercontent.com/79740955/141791678-ec4fa3e3-ed6f-4188-a67f-a50ccb8abc69.png)
The same happens with the OSM roads map layer.

@meomancer I've been looking into a possible solution to this. There is a getlegendgraphics parameter named hideEmptyRules: hides rules that are not matching any feature. Applicable only if countMatched is true (from geoserver docs). I'm still unsure if this would resolve the issue, so can you replace the getLegendGraphics request with this one: https://somaliland.gep.kartoza.com/geoserver/ows?service=WMS&request=GetLegendGraphic&format=image/png&WIDTH=20&HEIGHT=20&LAYER=geonode:somaliland_osm_waterways&STYLE=geonode_somaliland_osm_waterways&legend_options=fontAntiAliasing:true;fontSize:12;forceLabels:on;countMatched:true;hideEmptyRules:true&access_token=NudhtbRnlG7YyQ7FmdWwqbzjvr8HcJ
Just want to see if works, have no other of testing atm.

**Comment by NyakudyaA** [comment]
@vermeulendivan Can you check if you can use an alternate getlegend graphic as we can do in QGIS Server instances
![legend-p](https://user-images.githubusercontent.com/2510900/141794564-57fbf6fe-9260-4926-862c-9e17b173b05e.png)

**Comment by vermeulendivan** [comment]
@NyakudyaA Cool, will have a look at that.

**Comment by lkwalke4** [comment]
@vermeulendivan any update here?

**Comment by vermeulendivan** [comment]
@lkwalke4 Fixed. The same had to be done for osm roads, and had also been done. 
![image](https://user-images.githubusercontent.com/79740955/142614028-3ae4efdf-2c6a-486f-b5b5-29e46782ee7f.png)
