### ISSUE TITLE
Basemap background poorly matches coastline

### ISSUE THREAD

**Issue by lkwalke4** [kartoza/least-cost-electrification-somaliland#16]
Hi Seabilwe. Can you please improve how the basemap background looks around the Somaliland coastline?

Thank you.

![image](https://user-images.githubusercontent.com/18428984/141841236-20c65011-bb1b-47e5-8215-2002e25dac21.png)

**Comment by seabilwe** [comment]
Hi @vermeulendivan were you referring to this layer: https://somaliland.gep.kartoza.com/layers/somaliland_elevation:geonode:somaliland_elevation? if not, which one is it?

**Comment by vermeulendivan** [comment]
Hi @seabilwe The above example (figure 5) is in the SEP and its the Somaliland basemap which displays as such. Likely what happened is that the basemap were clipped/masked using a layer which is inaccurate along the coast (or has a poor resolution). Which layer were used to perform clipping/masking?
![image](https://user-images.githubusercontent.com/79740955/141942622-ba8fec7b-9956-41ae-9950-6960031e0077.png)
The elevation also looks poor along the coast, but that is a result of the poor resolution of the DEM. @seabilwe I'm going to send a DM in slack in the chat between you, me and Lindsay.

**Comment by lkwalke4** [comment]
We will close this issue as Seabilwe stated that the white/mask layer was made directly from the administrative boundaries received directly from Somaliland.
