### ISSUE TITLE
Toggle Layers

### ISSUE THREAD

**Issue by lkwalke4** [kartoza/least-cost-electrification-somaliland#19]
Hi Irwan,

Can you please add the following layers to the toggle layers functionality in the SEP?

- Somalia Interconnection
- Somalia/Ethiopia Interconnection
- Ethiopian Interconnection

There may be a few more to come. Thank you!

**Comment by meomancer** [comment]
could you provide the layer link to the geonode please @lkwalke4 ?

Size: 1

**Comment by lkwalke4** [comment]
https://somaliland.gep.kartoza.com/layers/geonode_data:geonode:somalia_interconnection

**Comment by lkwalke4** [comment]
https://somaliland.gep.kartoza.com/layers/geonode_data:geonode:ethiopia_somalia_interconnection

**Comment by lkwalke4** [comment]
https://somaliland.gep.kartoza.com/layers/geonode_data:geonode:ethiopia_interconnection

**Comment by lkwalke4** [comment]
There you go @meomancer

**Comment by meomancer** [comment]
This is deployed @lkwalke4 
please check it

**Comment by lkwalke4** [comment]
Looks great! Thank you so much @meomancer
