### ISSUE TITLE
GIS Layer Selector

### ISSUE THREAD

**Issue by timlinux** [kartoza/least-cost-electrification-somaliland#2]
![image](https://user-images.githubusercontent.com/178003/133096610-15fe4b26-f63b-49a7-95a3-5441c83e750f.png)

We should have a layer selector like we have for Benin

Probably want to use layers that are not in the base map

**Comment by meomancer** [comment]
could you list what layers should i show fro geonode @timlinux ?
https://somaliland.gep.kartoza.com/layers/?limit=5&offset=0

**Comment by lkwalke4** [comment]
For Benin, we have:
-Health sites
-Schools
-Distribution lines
-Transmission lines
-Sites PV

@timlinux just pinging you to specify any other specific layers you'd like in the layer selector.

**Comment by lkwalke4** [comment]
@meomancer did we make any progress on getting this layer selector in place?

**Comment by meomancer** [comment]
hi @lkwalke4 

-Distribution lines
-Transmission lines
-Sites PV

those layers are specifically for benin, so we don't have somaliland for now (but we can include if client has this layer and add it on geonode)

Here are the layers that we have for now (already deployed)
![Selection_209](https://user-images.githubusercontent.com/4530905/135986797-bff366cd-5c41-4be9-a049-e2c4745ed7a4.png)

Please check https://somaliland.gep.kartoza.com/layers/?limit=5&offset=0 for layers that are needed to be included as overlay

**Comment by lkwalke4** [comment]
Thank you @meomancer . As we get those other layers added to the SDI, I will ask you to add them as needed to the layer selector. Thank you!

**Comment by meomancer** [comment]
This is done
the next layers is in this ticket
https://github.com/kartoza/least-cost-electrification-somaliland/issues/19
