### ISSUE TITLE
We need to create a custom base map

### ISSUE THREAD

**Issue by timlinux** [kartoza/least-cost-electrification-somaliland#3]
@seabilwe to make the basemap in GeoServer

@meomancer please swap out the OSM basemap

Most important is to reflect the national boundary of Somaliland.

**Comment by seabilwe** [comment]
The layers used for the custom basemap are the OSM layers that have already been loaded on the platform. The Country and region boundary were provided by the World Bank team.

Three layer styles were updated for better viewing and removing the clutter in the map.
- OSM roads - fixed scale rendering of the symbol
-  OSM place name - adjusted scale rendering of the labels
-  Region boundary - added rule-based labelling for the labels to render at different scales and not creating confusion with the place names labels.

![Peek 2021-09-15 13-32](https://user-images.githubusercontent.com/56301949/133425848-1f72ecb1-1879-4660-8a8e-fbca1d747772.gif)

**Comment by lkwalke4** [comment]
@seabilwe has mentioned that she is working on adjusting some labels and styling and that review of the basemap will be ready on Wednesday.

**Comment by seabilwe** [comment]
@lkwalke4 

Latest version of the basemap: https://somaliland.gep.kartoza.com/geoserver/web/wicket/bookmarkable/org.geoserver.web.data.layergroup.LayerGroupPage?5&filter=false

![Peek 2021-09-23 00-01](https://user-images.githubusercontent.com/56301949/134428023-3cecb699-474a-46a4-bd2a-868330aa3e4f.gif)

**Comment by lkwalke4** [comment]
@seabilwe could you check with @NyakudyaA and verify that everything looks good with the basemap? If so, let's make it into the default basemap across the entire platform - CC @meomancer - so that as they explore the platform they're not seeing the incorrect boundaries that OSM has.

**Comment by meomancer** [comment]
yes @lkwalke4 
the issue that they reported was on mapbox basemap (that we are using now) does not have administrative for somaliland.
they want the basemap to show somaliland administrative

![Selection_202](https://user-images.githubusercontent.com/4530905/135804824-166c8db7-8a18-4e4a-a7a2-4d26e418da44.png)

They just want to have boundary of the somaliland (and also the text) into the somaliland
And also the district.

**Comment by seabilwe** [comment]
@meomancer can you grab them from the platform:https://somaliland.gep.kartoza.com/layers/?limit=5&offset=0&title__icontains=boundary&abstract__icontains=boundary&purpose__icontains=boundary&f_method=or 

because they have already been uploaded

**Comment by meomancer** [comment]
thank you @seabilwe 
could you change the duplicate text style? There are duplication in specific zoom
![Selection_204](https://user-images.githubusercontent.com/4530905/135972241-54893311-41af-4042-971f-03d8dc121b47.png)

i think we can just put the text in the center?

**Comment by NyakudyaA** [comment]
> thank you @seabilwe could you change the duplicate text style? There are duplication in specific zoom ![Selection_204](https://user-images.githubusercontent.com/4530905/135972241-54893311-41af-4042-971f-03d8dc121b47.png)
> 
> i think we can just put the text in the center?

This is because of meta tiling. Can you try to do a centroid placement for the labels?

```
<se:Geometry>
    <ogc:Function name="centroid">
         <ogc:PropertyName>geom</ogc:PropertyName>
    </ogc:Function>
</se:Geometry>
```

**Comment by meomancer** [comment]
hi @lkwalke4 @seabilwe @timlinux 
the basemap already added and deployed on SEP
thank you @seabilwe 

https://somaliland.gep.kartoza.com/gep/explore/sol-1

Please check it

**Comment by seabilwe** [comment]
Hi @NyakudyaA, I added the centroid function to the SLD style for the region boundary layer. The confusion that I have at the moment is, when I apply the style, the layer does not render even on the GeoNode side. When I want to preview the layer in GeoServer, it gives out a wms file with this info:


```
<?xml version="1.0" encoding="UTF-8" standalone="no"?><!DOCTYPE ServiceExceptionReport SYSTEM "http://somaliland.gep.kartoza.com/geoserver/schemas/wms/1.1.1/WMS_exception_1_1_1.dtd?access_token=rlFPiSpdBflQ3hmg8WUjxp5nlRwxKs"> <ServiceExceptionReport version="1.1.1" >   <ServiceException>
      The requested Style can not be used with this layer.  The style specifies an attribute named &apos;geom&apos;, not found in the &apos;geonode:somaliland_region_boundary&apos; layer
</ServiceException></ServiceExceptionReport>
```

When removing the centroid function, the layer renders fine. But What I am noticing is when I preview the layer on GeoServer and GeoNode, the centroid (initially applied when styling in QGIS) of the labels is maintained, except when the layer is taken to the SEP, that's where the duplication of labels occurs.

GoeNode
![Peek 2021-10-05 10-31](https://user-images.githubusercontent.com/56301949/135989392-d62d6fdb-6925-4b71-af2b-f97dce32cce8.gif)

GeoServer
![Peek 2021-10-05 10-33](https://user-images.githubusercontent.com/56301949/135989531-1a31ecde-02f1-4f3d-a3ef-eea2b65db89d.gif)

SEP
![Peek 2021-10-05 10-32](https://user-images.githubusercontent.com/56301949/135989662-a3f8eb82-bdb2-41eb-84a8-f19a299f5fce.gif)

**Comment by seabilwe** [comment]
> hi @lkwalke4 @seabilwe @timlinux the basemap already added and deployed on SEP thank you @seabilwe
> 
> https://somaliland.gep.kartoza.com/gep/explore/sol-1
> 
> Please check it

Thank you, @meomancer, I'm still not happy with the region boundary label and its duplication, but the rest of the features in the basemap are looking okay. I will continue to fix the issue

**Comment by NyakudyaA** [comment]
> Hi @NyakudyaA, I added the centroid function to the SLD style for the region boundary layer. The confusion that I have at the moment is, when I apply the style, the layer does not render even on the GeoNode side. When I want to preview the layer in GeoServer, it gives out a wms file with this info:
> 
> ```
> <?xml version="1.0" encoding="UTF-8" standalone="no"?><!DOCTYPE ServiceExceptionReport SYSTEM "http://somaliland.gep.kartoza.com/geoserver/schemas/wms/1.1.1/WMS_exception_1_1_1.dtd?access_token=rlFPiSpdBflQ3hmg8WUjxp5nlRwxKs"> <ServiceExceptionReport version="1.1.1" >   <ServiceException>
>       The requested Style can not be used with this layer.  The style specifies an attribute named &apos;geom&apos;, not found in the &apos;geonode:somaliland_region_boundary&apos; layer
> </ServiceException></ServiceExceptionReport>
> ```
> 
> When removing the centroid function, the layer renders fine. But What I am noticing is when I preview the layer on GeoServer and GeoNode, the centroid (initially applied when styling in QGIS) of the labels is maintained, except when the layer is taken to the SEP, that's where the duplication of labels occurs.
> 
> GoeNode ![Peek 2021-10-05 10-31](https://user-images.githubusercontent.com/56301949/135989392-d62d6fdb-6925-4b71-af2b-f97dce32cce8.gif)
> 
> GeoServer ![Peek 2021-10-05 10-33](https://user-images.githubusercontent.com/56301949/135989531-1a31ecde-02f1-4f3d-a3ef-eea2b65db89d.gif)
> 
> SEP ![Peek 2021-10-05 10-32](https://user-images.githubusercontent.com/56301949/135989662-a3f8eb82-bdb2-41eb-84a8-f19a299f5fce.gif)
@seabilwe  Just make sure the geometry column should be named accordingly in the example I gave you it was named `geom` maybe for your layer it is called `the_geom`. Just check on the layer attributes

**Comment by seabilwe** [comment]
Thank you @NyakudyaA, I kept copying and pasting the text with `geom` instead of the one I had changed. Thanks again.
@meomancer all is good now

![Peek 2021-10-05 10-59](https://user-images.githubusercontent.com/56301949/135993196-87ca68d1-777c-4d7a-aa01-f25b4bf24311.gif)

**Comment by lkwalke4** [comment]
![image](https://user-images.githubusercontent.com/18428984/136289197-a4f808b6-93c7-4a51-b26e-42c31c1ea034.png)

Hi @seabilwe . Can you please let me know where you're at with everything? Also, can we please adjust the boundaries to have more appropriate lines? These are too thick and fuzzy. I will have some feedback on a variety of other elements of the basemap in our meeting on Monday.

**Comment by seabilwe** [comment]
HI @lkwalke4 

The line thickness of the boundary is at 0.3 mm, I am not sure why the basemap is fuzzy and that the thickness of the boundary looks too thick when it's deployed on the SEP, the preview of the basemap alone is fine. I assume it could be the raster layer overlaid on top of it.

**Comment by meomancer** [comment]
Hi @seabilwe @lkwalke4 
I will check it on the sep, maybe there is wrong config or size on sep

**Comment by meomancer** [comment]
hi @seabilwe @lkwalke4 
The layer is fixed on SEP
thank you for the layer @seabilwe 

![Selection_216](https://user-images.githubusercontent.com/4530905/136375005-f9c3f7c3-e060-4a3f-be85-084e8435273c.png)

**Comment by seabilwe** [comment]
The OSM basemap in the SEP is to be creating duplcate names of towns and cities which acuses confusion with  the basemap created on geoserver 
![image](https://user-images.githubusercontent.com/56301949/141778566-a65bba3e-143f-4f3c-894c-25ed9e8d6b8e.png)
![image](https://user-images.githubusercontent.com/56301949/141778646-8203c400-8128-4289-ace4-268eb0e12fb6.png)

**Comment by lkwalke4** [comment]
@seabilwe I am going to close this issue because I'd like to create smaller, actionable tickets for some basemap issues. I am moving your most recent comment to this ticket: https://github.com/kartoza/least-cost-electrification-somaliland/issues/15
