### ISSUE TITLE
Odd Formatting on Homepage

### ISSUE THREAD

**Issue by lkwalke4** [kartoza/least-cost-electrification-somaliland#5]
There are some odd formatting issues happening on the homepage - https://somaliland.gep.kartoza.com/

![image](https://user-images.githubusercontent.com/18428984/134040564-5d32a790-db68-4aee-813b-19ce957646e8.png)

**Comment by lkwalke4** [comment]
![image](https://user-images.githubusercontent.com/18428984/134049470-19f46a9e-50c8-4a0f-988f-e524f9dce0f4.png)

@timlinux any objections to moving the SEP link to the end of the links? Visually I think it would make more sense.

**Comment by lkwalke4** [comment]
@meomancer could you please look at these formatting issues, and help get them corrected?

**Comment by meomancer** [comment]
This has been updated and deployed
could you check this @lkwalke4 ?

About f and i, it is coming from the font
You can check the platform in here: 
https://electrifynow.energydata.info/

**Comment by lkwalke4** [comment]
![image](https://user-images.githubusercontent.com/18428984/136288745-a42c27fe-7122-4a9d-bd5b-eef0718dee72.png)

Hi Irwan! It is looking better. Thank you. On a different note - I notice that we're displaying a broken layer here. How easy is it to change the highlighted layers?

![image](https://user-images.githubusercontent.com/18428984/136288909-34d09586-ece6-4dbb-b2c0-88e1e5161de1.png)

Also, I notice that the page says "example.com" in tab form. Can this be fixed?

**Comment by meomancer** [comment]
hi @lkwalke4 
the "example.com" has been changed

Also for remove and add the map, the admin can go to https://somaliland.gep.kartoza.com/en/admin/custom/mapslugmapping/
and just check/uncheck the "Featured" column
