### ISSUE TITLE
Education facilities does not render in lower zoom

### ISSUE THREAD

**Issue by meomancer** [kartoza/least-cost-electrification-somaliland#9]
https://somaliland.gep.kartoza.com/layers/geonode_data:geonode:somaliland_unicef_education_facilities

When we zoom out, the data does not rendered. We need to zoom in to be able to see it
Can you check it @seabilwe ?

**Comment by NyakudyaA** [comment]
> https://somaliland.gep.kartoza.com/layers/geonode_data:geonode:somaliland_unicef_education_facilities
> 
> When we zoom out, the data does not rendered. We need to zoom in to be able to see it Can you check it @seabilwe ?

If the points are too much and you feel that this could be a distraction please add SLD clustering at those scales and switch to your style at the scale that makes sense

https://docs.geoserver.geo-solutions.it/edu/en/wps/rendering_tx.html

**Comment by seabilwe** [comment]
@meomancer have a look at the layer again

**Comment by meomancer** [comment]
Nice, thank you @seabilwe 
it is working well
